import BaseSeeder from '@ioc:Adonis/Lucid/Seeder'
import Occupation from 'App/Models/Occupation'

export default class extends BaseSeeder {
  public async run() {
    await Occupation.createMany([
      { name: 'aerospace engineer' },
      { name: 'architect' },
      { name: 'art director' },
      { name: 'artist' },
      { name: 'astronomer' },
      { name: 'athlete' },
      { name: 'author' },
      { name: 'baker' },
      { name: 'barber' },
      { name: 'bartender' },
      { name: 'bus driver' },
      { name: 'carpenter' },
      { name: 'cartographer' },
      { name: 'chef' },
      { name: 'chief executive' },
      { name: 'cleaner' },
      { name: 'composer' },
      { name: 'criminal investigator' },
      { name: 'dancer' },
      { name: 'dentist' },
      { name: 'designer' },
      { name: 'detective' },
      { name: 'dietitian' },
      { name: 'cop' },
      { name: 'director' },
      { name: 'doctor' },
      { name: 'electrician' },
      { name: 'engineer' },
      { name: 'entertainer' },
      { name: 'environmental scientist' },
      { name: 'epidemiologist' },
      { name: 'escort' },
      { name: 'gamer' },
      { name: 'youtuber' },
      { name: 'streamer' },
      { name: 'prostitute' },
      { name: 'thief' },
      { name: 'terrorist' },
      { name: 'soldier' },
      { name: 'farmer' },
      { name: 'firefighter' },
      { name: 'graphic designer' },
      { name: 'hairdresser' },
      { name: 'historian' },
      { name: 'history teacher' },
      { name: 'host' },
      { name: 'hostess' },
      { name: 'housekeeping cleaner' },
      { name: 'hunter' },
      { name: 'inspector' },
      { name: 'interpreter' },
      { name: 'interviewer' },
      { name: 'investigator' },
      { name: 'jailer' },
      { name: 'janitor' },
      { name: 'jeweler' },
      { name: 'judge' },
      { name: 'lawyer' },
      { name: 'lifeguard' },
      { name: 'locksmith' },
      { name: 'machinist' },
      { name: 'maid' },
      { name: 'makeup artist' },
      { name: 'management analyst' },
      { name: 'management occupation' },
      { name: 'manager' },
      { name: 'manicurist' },
      { name: 'mathematician' },
      { name: 'mechanic' },
      { name: 'music director' },
      { name: 'musician' },
      { name: 'nutritionist' },
      { name: 'painter' },
      { name: 'paramedic' },
      { name: 'pediatrician' },
      { name: 'pedicurist' },
      { name: 'performer' },
      { name: 'pharmacist' },
      { name: 'photographer' },
      { name: 'physician' },
      { name: 'physicist' },
      { name: 'private detective' },
      { name: 'producer' },
      { name: 'psychiatrist' },
      { name: 'psychologist' },
      { name: 'radio operator' },
      { name: 'receptionist' },
      { name: 'reporter' },
      { name: 'runner' },
      { name: 'singer' },
      { name: 'software developer' },
      { name: 'surgeon' },
      { name: 'taxi driver' },
      { name: 'teacher' },
      { name: 'technician' },
      { name: 'therapist' },
      { name: 'tour guide' },
      { name: 'translator' },
      { name: 'trapper' },
      { name: 'travel agent' },
      { name: 'travel guide' },
      { name: 'veterinarian' },
      { name: 'waiter' },
      { name: 'waitress' },
      { name: 'writer' },
      { name: 'zoologist' },
    ])
  }
}
